### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [SonarSource/docker-sonarqube#103]
I want to build this image on arm64 architecture but I'm not sure this file can be support arm64.https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.5.zip

**Comment by tianon** [comment]
Since `sonarqube` is `FROM openjdk:...`, this `Dockerfile` _should_ just work as-is with any the architectures supported by `openjdk` (https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/openjdk#L63, `amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x`), with the caveat that Alpine support needs to wait on https://github.com/gliderlabs/docker-alpine/issues/304.

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:

**Comment by kmleow** [comment]
Hi @tianon,

According to https://hub.docker.com/_/sonarqube/, it says supported architecture is amd64 only.
Perhaps that page should be updated to reflect the true list?

Thank you

**Comment by tianon** [comment]
@kmleow correct, that's what this issue is discussing -- the image maintainers need to commit to at least accepting that the software will be available for other arches (which is what we expect for "support" from the official images side).

It'd probably be helpful to also have someone verify my assumption above and actually test building and running `sonarqube` on these other arches.

Once that's done, https://github.com/docker-library/official-images/blob/master/library/sonarqube will need to be updated to reference the actual supported architectures, which will then cause them to be built/published, and the "supported architectures" list to be updated.

**Comment by tianon** [comment]
I've just built `7.1` on `arm64v8` successfully, and it appears to run just fine:
```
2018.06.05 20:37:07 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
```
(as expected -- after a ton of other normal startup output :smile:)

@Godin any objections to officially supporting other architectures as has been proposed here?  Does the upstream SonarQube project support other architectures already?

**Comment by Godin** [comment]
@tianon first of all thank you for your help, testing, explanations and very good questions in this thread :heart: 

AFAIK SonarQube is extensively tested only on `amd64`. Also I have serious doubts that Elasticsearch (one of very sensitive and core components in SonarQube) officially supports anything else - quoting https://www.elastic.co/support/matrix :

> currently only support and test x86_64 architectures.

Similarly (exactly from the same source above) in fact even support of `alpine` variant is highly questionable from official point of view.

And to be fully honest and transparent with you even status of `Docker` image as one of official distribution channels of SonarQube by SonarSource is questionable ( CC @simonbrandhof ) - from questions/answers, community/paid support, updates/maintainance, testing, promotion, etc points of view. I personally don't wanna altruistically take additional work/risks on my shoulders by growing matrix. IMO we first need to clarify all this internally. Thank you for understanding.

**Comment by lag-linaro** [comment]
@Godin I'm going to add a "me too" for ARM64 support.  There is a big push from some silicon vendors and ARM itself to ensure the architecture is as broadly supported as X86 is currently.  It is paramount that Enterprise based projects such as this one 'just work'.  Obviously I can appreciate that it's less work to officially support only a single architecture, but since when have we used that as excuse not to do the right thing in Open Source - or any other self respecting software project for that matter.

Seeing as this project seems to work (build, run) on ARM64 already, is there any chance we can add it to the list of supported architectures, so at least `docker pull` can work.  Then add a caveat to the tune of, ARM64 support is provided for testing purposes only and is not officially supported/funded by this project currently, etc etc.

**Comment by simonbrandhof** [comment]
I confirm that in the current state SonarQube is not supported on ARM64. As a consequence the Docker image should not be marked as compatible.

I suggest to discuss about the need to support ARM64 on the [community forum](http://community.sonarsource.com/) of SonarSource. Thanks for your understanding.
