### ISSUE TITLE
Unable to use LDAP plugin

### ISSUE THREAD

**Issue by tylersmith34** [SonarSource/docker-sonarqube#142]
I'm pulling down the 6.0 version of the container and am running into a problem with the LDAP plugin.  I'm containerizing my existing instance and will upgrade to the latest LTS once I'm able to convert.

My Dockerfile and output are attached.

[Dockerfile.txt](https://github.com/SonarSource/docker-sonarqube/files/1668458/Dockerfile.txt)
[output.txt](https://github.com/SonarSource/docker-sonarqube/files/1668459/output.txt)
[sonar.properties.txt](https://github.com/SonarSource/docker-sonarqube/files/1668463/sonar.properties.txt)

If I remove the LDAP section then it works, so it's not presence of the plugin itself.  These exact settings work when I use a plain server approach, running at AWS EC2 using the AWS AMI.

**Comment by Godin** [comment]
First of all seems that you have overlapping lines in `output.txt`
```
Caused bat org...
```
normally should look like
```
Caused by ...
    at ...
```
and so this doesn't allow to see root cause.

Then your `sonar.properties.txt` contains
```
ldap.url=ldap://URL goes here
ldap.bindDn=Full CN goes here
```
and hard to believe that these exact settings work without Docker.

Example of Docker usage with LDAP configuration from https://github.com/SonarSource/sonar-ldap works fine with `6.0`
```diff
diff --git i/docker/Dockerfile.sonarqube w/docker/Dockerfile.sonarqube
index fd2943e..b121d7d 100644
--- i/docker/Dockerfile.sonarqube
+++ w/docker/Dockerfile.sonarqube
@@ -1,2 +1,2 @@
-FROM sonarqube:lts-alpine
+FROM sonarqube:6.0
```
(needs a bigger update/fix to work with more recent images (e.g. LTS) where `sonarqube` (non-root) user is used instead of `root`, but that's completely different story)

So most likely you have configuration/environment issue and hence unrelated to this issue tracker that is solely about base image.

And in any case for questions/to get help/etc please use another channel (https://www.sonarqube.org/community/feedback/) - e.g. [Google Group](https://groups.google.com/forum/#!forum/sonarqube/), because it provides access to far more wider range of people that can help you in comparison with observers of this bug tracker.

Thank you for your understanding.

**Comment by tylersmith34** [comment]
I obviously removed settings from the sonar properties that provide insight into my company and those aren't the real values. The configuration I put in the container is exactly the same as my non container server and your container chokes so I do believe it to be a problem with the base image.

**Comment by Godin** [comment]
Please provide non-damaged log without overlapping lines.

**Comment by tylersmith34** [comment]
I looked at the LDAP plugin to follow how it passes the certificate and now I'm getting a different error message that relates to LDAP specifically.  Please consider this issue moot (it's already closed).  Thank you for the link to the LDAP repo.

**Comment by Godin** [comment]
> I'm getting a different error message that relates to LDAP specifically.

What's the connection with this Docker image if it "relates to LDAP specifically"? Once again - if this is generic question, please consider usage of another channel (https://www.sonarqube.org/community/feedback/) , because it provides access to far more wider range of people that can help you in comparison with observers of this bug tracker.

> Please consider this issue moot (it's already closed).

Nevertheless - no problem to reopen this one, but once again - please provide non-damaged log without overlapping lines showing a error message.

**Comment by tylersmith34** [comment]
I fixed my problem, the ldap plugin wasn't downloaded correctly. I thought
that it was and that the base image from this repo wasn't opening the ldap
jar but that wasn't the case.

**Comment by Godin** [comment]
> I fixed my problem

That's cool! Glad to hear, thank you for notification.

**Comment by praqmaTim** [comment]
OK, This may sound like a dumb question, but it is what it is. Does SonarQube 7.1 have built in support for LDAP or do I need to install this plugin? The documentation at Sonar is a bit confusing. It doesn't say whether the support is through this plugin or supported out of the box.

https://docs.sonarqube.org/display/SONAR/LDAP+Integration
