### ISSUE TITLE
Plugins persistence.

### ISSUE THREAD

**Issue by pasquinid** [SonarSource/docker-sonarqube#146]
Hi, I made my own sonar image in witch I already have some plugins installed. Also, the mysql database is persistent and has all the data in there. But why the sonar keeps deleting all the plugins (and quality profiles) when I remove the container and run him again with the same mysql database? Am I forced to use a volume :( ? Is there another solution? Thanks!

**Comment by nixel2007** [comment]
The only way to have persistent data in docker is volumes. So yes, you need to add volume for extensions' dir

**Comment by pasquinid** [comment]
I understand. But the thing is that the image used already have the data. So when it starts, it already have the plugins in it. The problem is that the sonarqube deletes them after a bit of time.

**Comment by Godin** [comment]
@pasquinid I believe that you'll find answer on your question in https://github.com/SonarSource/docker-sonarqube/issues/112#issuecomment-338277087

**Comment by pasquinid** [comment]
Thank you!

**Comment by jamesboehmer** [comment]
Sorry to bring this back up, but I'm not sure how docker volumes or the description in #112 solves the problem.  When I click `install` in the UI, it downloads the jar file to `/opt/sonarqube/extensions/downloads/`, and upon soft restart, copies the jar to `/opt/sonarqube/extensions/plugins/`.

If I run the container with `/opt/sonarqube/extensions/downloads` as a volume, the downloaded files will get deleted, and the persistence is useless.

If I run the container with `/opt/sonarqube/extensions/plugins` as a volume, the container will launch for the first time with no bundled plugins.

Is this to say I should copy all the bundled jars out of the image, into my volume, and then run the container with the volume mounted at `/opt/sonarqube/extensions/plugins`?  If I run a swarm, they will all need this bespoke-prepared volume.  This smells like an awful docker anti-pattern.

**Comment by Godin** [comment]
@jamesboehmer 

Exactly as in my comment https://github.com/SonarSource/docker-sonarqube/issues/112#issuecomment-338277087 - content in filesystem of image is:

```
$ docker run -it --rm sonarqube:6.7.1-alpine ls -R /opt/sonarqube/extensions/
/opt/sonarqube/extensions/:
jdbc-driver  plugins

/opt/sonarqube/extensions/jdbc-driver:
oracle

/opt/sonarqube/extensions/jdbc-driver/oracle:
README.txt

/opt/sonarqube/extensions/plugins:
README.txt
```

Bundled plugins reside in another directory:

```
$ docker run -it --rm sonarqube:6.7.1-alpine ls /opt/sonarqube/lib/bundled-plugins
sonar-csharp-plugin-6.5.0.3766.jar
sonar-flex-plugin-2.3.jar
sonar-java-plugin-4.15.0.12310.jar
sonar-javascript-plugin-3.2.0.5506.jar
sonar-php-plugin-2.11.0.2485.jar
sonar-python-plugin-1.8.0.1496.jar
sonar-scm-git-plugin-1.3.0.869.jar
sonar-scm-svn-plugin-1.6.0.860.jar
sonar-typescript-plugin-1.1.0.1079.jar
sonar-xml-plugin-1.4.3.1027.jar
```

and will be installed into `/opt/sonarqube/extensions/plugins`. So there is no problem to mount directory that does not contain bundled plugins, because in the image this directory anyway does not contain them.

Thus

> If I run the container with `/opt/sonarqube/extensions/plugins` as a volume, the container will launch for the first time with no bundled plugins.

is wrong

> Is this to say I should copy all the bundled jars out of the image, into my volume, and then run the container with the volume mounted at `/opt/sonarqube/extensions/plugins`?

and no - here is an example with mount of current empty directory as `/opt/sonarqube/extensions/plugins`:

```
$ ls -lA
total 0

$ docker run -it --rm -v ${PWD}:/opt/sonarqube/extensions/plugins sonarqube:6.7.1-alpine
...
2018.03.08 17:02:55 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarPython [python] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarQube :: Plugins :: SCM :: Git [scmgit] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarTS [typescript] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarC# [csharp] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin Flex [flex] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarQube :: Plugins :: SCM :: SVN [scmsvn] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarXML [xml] installed
2018.03.08 17:02:56 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarPHP [php] installed
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJava [java] installed
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJS [javascript] installed
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Flex / 2.3 / 79167f762219bea1fd181ff5ef6ca4b34abd1675
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarC# / 6.5.0.3766 / 6011a1e9fb002edb044ae3092d92bcfb7d9d8a2d
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 3.2.0.5506 / 86da09565f891121df248835665f5d8ed98772b6
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 4.15.0.12310 / 572454b93016ec73a53fe0e07b2ffdc356d21ba9
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPHP / 2.11.0.2485 / 741861a29e5f9a26c6c99c06268facb6c4f4a882
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPython / 1.8.0.1496 / 3fe3bc4d0273a5721ea2fb368dc45b1bb82fede3
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarQube :: Plugins :: SCM :: Git / 1.3.0.869 / 4da53e3f9e55f4f2e5796625cb0c5768ed152079
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarQube :: Plugins :: SCM :: SVN / 1.6.0.860 / 2111fdbd1dddda4ad6d4ed6486fd0b18c1010d3b
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarTS / 1.1.0.1079 / 042c9e65239a47d92d305f9767f730b3cc1e5ed3
2018.03.08 17:02:57 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarXML / 1.4.3.1027 / 39588245cecf538bb27be4e496ff303b0143d20b
2018.03.08 17:02:57 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
...

$ ls -lA
total 40464
-rw-r--r-- 1 evgeny.mandrikov wheel 2703958 Dec 18 11:44 sonar-csharp-plugin-6.5.0.3766.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 1618672 Dec 18 11:44 sonar-flex-plugin-2.3.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 6759535 Dec 18 11:44 sonar-java-plugin-4.15.0.12310.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 3355702 Dec 18 11:44 sonar-javascript-plugin-3.2.0.5506.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 3022870 Dec 18 11:44 sonar-php-plugin-2.11.0.2485.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 4024311 Dec 18 11:44 sonar-python-plugin-1.8.0.1496.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 3625962 Dec 18 11:44 sonar-scm-git-plugin-1.3.0.869.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 6680471 Dec 18 11:44 sonar-scm-svn-plugin-1.6.0.860.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 2250667 Dec 18 11:44 sonar-typescript-plugin-1.1.0.1079.jar
-rw-r--r-- 1 evgeny.mandrikov wheel 7368250 Dec 18 11:44 sonar-xml-plugin-1.4.3.1027.jar
```

> When I click install in the UI, it downloads the jar file to `/opt/sonarqube/extensions/downloads/`, and upon soft restart, copies the jar to `/opt/sonarqube/extensions/plugins/`.

> If I run the container with `/opt/sonarqube/extensions/downloads` as a volume, the downloaded files will get deleted, and the persistence is useless.

Yes - SonarQube application downloads plugins into `/opt/sonarqube/extensions/downloads/` and on (re)start installs them into `/opt/sonarqube/extensions/plugins/`.

And also **while plugins are not stored in database, fact of their deployment is stored** - again exactly as in https://github.com/SonarSource/docker-sonarqube/issues/112#issuecomment-338277087

So state of database should also be persisted.

In case of usage of embedded database its state is in `/opt/sonarqube/data`, so 

```
$ ls -l
total 0

$ mkdir downloads plugins data

$ docker run -d \
    -v ${PWD}/plugins:/opt/sonarqube/extensions/plugins \
    -v ${PWD}/downloads:/opt/sonarqube/extensions/downloads \
    -v ${PWD}/data:/opt/sonarqube/data \
    --name test \
    -p 9000:9000 \
    sonarqube:6.7.1-alpine
```

Now I click "install" in UI:

![1](https://user-images.githubusercontent.com/138671/37167310-dc06dc00-2301-11e8-9c57-2622b99628c2.png)

Click "restart":

![2](https://user-images.githubusercontent.com/138671/37167324-e256ce26-2301-11e8-9fb7-83e1e71a52a6.png)

And new plugin is installed:

![3](https://user-images.githubusercontent.com/138671/37167335-e66f1982-2301-11e8-9fa6-16ba3b6b377f.png)

and previous (including bundled) are still there:

```
$ docker exec test ls /opt/sonarqube/extensions/plugins
checkstyle-sonar-plugin-4.8.jar
sonar-csharp-plugin-6.5.0.3766.jar
sonar-flex-plugin-2.3.jar
sonar-java-plugin-4.15.0.12310.jar
sonar-javascript-plugin-3.2.0.5506.jar
sonar-php-plugin-2.11.0.2485.jar
sonar-python-plugin-1.8.0.1496.jar
sonar-scm-git-plugin-1.3.0.869.jar
sonar-scm-svn-plugin-1.6.0.860.jar
sonar-typescript-plugin-1.1.0.1079.jar
sonar-xml-plugin-1.4.3.1027.jar

$ curl -s http://localhost:9000/api/plugins/installed | jq ".plugins[].key"
"checkstyle"
"flex"
"csharp"
"javascript"
"java"
"php"
"python"
"scmgit"
"scmsvn"
"typescript"
"xml"

$ curl -s http://localhost:9000/api/plugins/installed | jq ".plugins[].key" | wc -l
11
```

and same `11` plugins even after restart of container:

```
$ docker stop test && docker start test
$ curl -s http://localhost:9000/api/plugins/installed | jq ".plugins[].key" | wc -l
11

$ docker restart test
$ curl -s http://localhost:9000/api/plugins/installed | jq ".plugins[].key" | wc -l
11
```

So I don't see what is your problem @jamesboehmer 

Also if

> ... swarm ... they all

means that you're trying to connect multiple SonarQube instances to the same database, then should be noted that this is impossible as of today and this has nothing to do with this Docker image - this is simply not supported by application (SonarQube).

Also in future please consider usage of https://www.sonarqube.org/community/feedback/ for questions about SonarQube, because of access to wider audiences of people who can help/answer than watchers of this repository. Thank you for your understanding.
