### ISSUE TITLE
Unable install `SVG Badges` into alpine version

### ISSUE THREAD

**Issue by standag** [SonarSource/docker-sonarqube#165]
Based on this issue https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/issues/44, plugin `SVG Badges` fails on restart of sonarqube. Can be solved in this image by the update of `ttf-dejavu`.  Do you think that is the correct place for putting fix here?

**Comment by simonbrandhof** [comment]
Hi @standag, I don't think it should be fixed in the SonarQube image for two reasons:
* supporting all the corner cases of different plugins and environments is an endless battle.
* the project badge feature is now [native since version 7.1](https://www.sonarsource.com/resources/product-news/news.html#2018-04-17-sonarqube-7-1-released). Installing the qualityinsight plugin is no longer needed.

Thanks for your understanding.
