### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by adrianblakey** [SonarSource/docker-sonarqube#190]
Please could you provide an update that exposes some environment variables to the image to support LDAP?

https://docs.sonarqube.org/display/SONAR/LDAP+Integration#LDAPIntegration-Configuration

**Comment by Godin** [comment]
No, we don't want to add tons of environment variables because properties already can be passed via command line - as a proof:

```
$ cat <<END > Dockerfile
FROM sonarqube:alpine
RUN cd /opt/sonarqube/extensions/plugins/ \
    && wget https://sonarsource.bintray.com/Distribution/sonar-ldap-plugin/sonar-ldap-plugin-2.2.0.608.jar
END

$ docker build -t ldap-example .

$ docker run -it --rm ldap-example -Dsonar.security.realm=LDAP -Dldap.url=ldap://my-ldap-server:10389
```

will perform attempt to connect to LDAP server

```
...
2018.07.31 19:01:03 INFO  web[][o.s.p.l.LdapContextFactory] Test LDAP connection: FAIL
org.sonar.plugins.ldap.LdapException: Unable to open LDAP connection
...
Caused by: javax.naming.CommunicationException: my-ldap-server:10389
...
Caused by: java.net.UnknownHostException: my-ldap-server
...
```

**Comment by adrianblakey** [comment]
TY!

**Comment by culyzhao** [comment]
Is ldap default plugin in soanrqube LTS image?
When I add volumes to map data folder in docker-compose.yml
     volumes:
       - "/opt/sonarqube/data:/opt/sonarqube/data"
I can't startup soanrqube, I got these message
sonarqube    | Caused by: org.sonar.api.utils.SonarException: Realm 'LDAP' not found. Please check the property 'sonar.security.realm' in conf/sonar.properties
sonarqube    |  at org.sonar.server.user.SecurityRealmFactory.<init>(SecurityRealmFactory.java:51)
sonarqube    |  at org.sonar.server.user.SecurityRealmFactory.<init>(SecurityRealmFactory.java:71)
sonarqube    |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sonarqube    |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sonarqube    |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
sonarqube    |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
sonarqube    |  at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
sonarqube    |  at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
sonarqube    |  at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
sonarqube    |  at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
sonarqube    |  at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
sonarqube    |  at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
sonarqube    |  at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
sonarqube    |  at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
sonarqube    |  at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
sonarqube    |  at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:62)
sonarqube    |  ... 88 common frames omitted

But delete "/opt/sonarqube/data:/opt/sonarqube/data", LDAP works well.
my docker-composer.yml
version: "3"
services:
   db:
     image: postgres:10
     restart: always
     container_name: postgres
     ports:
       - "5432:5432" 
     environment:
       - POSTGRES_USER=sonar 
       - POSTGRES_PASSWORD=sonar
  
   adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080
  
   sonarqube:
     image: sonarqube:lts
     command: -Dsonar.security.realm=LDAP -Dldap.url=ldap://10.0.1.10 -Dldap.bindDn=xxx -Dldap.bindPassword=xxx -Dldap.user.baseDn=xxx
     container_name: sonarqube
     ports:
       - "9000:9000"
       - "9092:9092"
     volumes:
       - "/etc/localtime:/etc/localtime:ro"
       - "/opt/postgres/data:/var/lib/postgresql/data"
       - "/opt/sonarqube/data:/opt/sonarqube/data"
     links:
       - db
     environment:
       - sonar.jdbc.username=sonar
       - sonar.jdbc.password=sonar
       - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
     ulimits:
       nproc: 65535
