### ISSUE TITLE
Provide a docker image for SonarQube Developer Edition

### ISSUE THREAD

**Issue by mind-blowing** [SonarSource/docker-sonarqube#223]
Currently there are no docker image for `SonarQube Developer Edition`, it will be nice if you will support it in your official docker repository.

**Comment by shadowXVll** [comment]
Also if anyone can provide some info about promotion from community to dev edition? In docker container. Thx in advance.

**Comment by bendavidpaz** [comment]
I agree with the previous two comments.  An image with the developer edition pre-installed would be great. Also an explanation of how to map container data sets to docker volumes would be great.   I plan to use postgres for the DB - in a separate container.

**Comment by Mitsufumi** [comment]
Yopii made great job. He prepared a docker image for SonarQube Developer Edition.
Thank you so much, Yopii!!

@bendavidpaz 
You might know it though, I don't recommend you to use DB in container. Container is ephemeral.

**Comment by MarkWillems** [comment]
Where can I test this?

**Comment by SeanTurner026** [comment]
Yopii did a great job. I built his docker image, modified the official helm chart values.yaml to use the image I built, navigated to /setup, upgraded my database, and everything works.

**Comment by simonbrandhof** [comment]
For reference: https://jira.sonarsource.com/browse/MMF-1604

**Comment by itshorty** [comment]
Is there already an expected release for the developer image?

**Comment by claasd** [comment]
What is blocking this PR?

**Comment by alexmngn** [comment]
Is there a way to upgrade the community edition docker image to use the developer edition?

**Comment by jcoeltjen** [comment]
There is a PR for 7.7 Developer Edition: #273

**Comment by ricardompcarvalho** [comment]
Does anyone know if there is an Enterprise Edition image?

**Comment by bdavis-tc** [comment]
> Does anyone know if there is an Enterprise Edition image?

**Community Edition**: official docker image is readily available and actively maintained and updated
https://hub.docker.com/_/sonarqube

From what I've seen on this topic; the status for **Enterprise Edition** is the same as **Developer Edition**.

- There may be 3rd party dockerfiles you can use to build an image.
- You might even be able to use the Community Image and install the license plugin.

(I haven't attempted yet, but I will most likely be expected to with-in the next few months.)

Here are some links to discussions I've found that I consider to be related to this topic:
- https://community.sonarsource.com/t/sonarqube-docker-images/4209
- https://community.sonarsource.com/t/supported-docker-container-version-of-sonarqube-developer-enterprise-edition/8954
- https://community.sonarsource.com/t/dev-edition-as-docker-image/5394/21

**Comment by fsanys** [comment]
The good thing is that your Server ID is linked to your JDBC URL. It means that after an upgrade and re-deployment your Server ID will remain the same and your licence is still gonna work.

Only two lines have to be changed in the Dockerfile from the Doccommunity to developer edition (Binaries download)
Example: https://github.com/fsanys/sonarqube-developer + https://cloud.docker.com/u/floriansanys/repository/docker/floriansanys/sonarqube-developer

**Comment by prodigy7** [comment]
Would be nice, seeing a updated up to date docker release for the developer edition! :-)

**Comment by pierre-guillot-sonarsource** [comment]
> Would be nice, seeing a updated up to date docker release for the developer edition! :-)

Hi, we are about to release a first experimental version for DE and EE. We are currently testing it internally to make sure everything is fine. Our intention is to have a public experimental image for DE/EE with SQ 8.0 version, gather feedback from the community, and release an officially supported image with SQ 8.1.

**Comment by fabricioepa** [comment]
I am looking forward to use this version, because I am currently working on running a DE docker image before get the license to my company.

**Comment by torstenwalter** [comment]
> > Would be nice, seeing a updated up to date docker release for the developer edition! :-)
> 
> Hi, we are about to release a first experimental version for DE and EE. We are currently testing it internally to make sure everything is fine. Our intention is to have a public experimental image for DE/EE with SQ 8.0 version, gather feedback from the community, and release an officially supported image with SQ 8.1.

A short update on this. It looks as if the beta images have been published two days ago as

```
sonarqube:8.0-developer-beta
sonarqube:8.0-enterprise-beta
```

**Comment by pbradly** [comment]
I've tried running the beta Developer edition docker image and have come up against a potential issue. 

Right now we are running a custom docker image of 7.8 (based on this [image](https://github.com/SonarSource/docker-sonarqube/pull/280/files)) deployed into a Kubernetes network. However when upgrading to 8.0 we get this error;

`Web server startup failed: Current version is too old. Please upgrade to Long Term Support version firstly.`

Know I understand that this issue is not due to the version of Sonarqube we're upgrading to but with the version of the SonarQube platform we're upgrading from. Ideally we would upgrade first to 7.9 and then move to 8. But there is no official docker image for 7.9. 

Is this a case were anyone wishing to move to the official docker image has to first create and migrate to a custom 7.9 docker image _before_ they can move to the official 8.0 version? Has anyone else come up against this issue when migrating?

**Comment by pierre-guillot-sonarsource** [comment]
@pbradly Thanks for this feedback. In your case, you can use any LTS edition to upgrade your database. For example, you can use the tag `7.9.1-community` from docker hub. This will downgrade your SQ to CE and upgrade the DB schema & data. Then you can use the brand-new 8.0 DE version, which will upgrade your DB to 8.0 and upgrade back to DE.

`Custom 7.8 DE image` -> `7.9.1-community` -> `8.0-developer-beta`

**Comment by pierre-guillot-sonarsource** [comment]
As @torstenwalter mentioned, beta version have been released under the following tags :
`8.0-community-beta`
`8.0-developer-beta`
`8.0-enterprise-beta`

Keep in mind that theses version are labelled `beta` because they changed a lot from the previous version, and we are happy to get feedback on them before declaring them as officially supported.

To be clear : the Dockerfile is beta, the SonarQube release is not.

Feedback is welcome on the [community](https://community.sonarsource.com/) or here with issues and PR.
