### ISSUE TITLE
Database "sonar" does not exists 

### ISSUE THREAD

**Issue by nygage** [SonarSource/docker-sonarqube#466]
Hello, I am using the docker compose script with Postgre but when I try to start the container it says this:

> sonarqube    | 2021.02.17 11:19:00 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://db:5432/sonar
sonarqube_db | 2021-02-17 11:19:00.743 UTC [33] FATAL:  database "sonar" does not exist
sonarqube    | 2021.02.17 11:19:00 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
sonarqube    | java.lang.IllegalStateException: Fail to connect to database
sonarqube    |  at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:87)
sonarqube    |  at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
sonarqube    |  at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)

What can i do?

Thanks

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @nygage ,

can you post the compose file that you are using?

**Comment by goyalg8** [comment]
Hi @tobias-trabelsi-sonarsource : I am having same issue while running Sonarqube (8.7 community) dockerfile on Azure App Service for Webapp containers (Linux). I am having the below issues:
ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
2021-02-25T23:11:37.558221777Z java.lang.IllegalStateException: Fail to connect to database

Please note: I have also included SSH part in sonarqube dockerfile.

Can I ask few questions here:
- what should be the value of SONARQUBE_WEB_JVM_OPTS in Azure app settings = ???
- where can I find the file (Sonar.properties): ??? 

Please help me with this..

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @goyalg8 ,

this sounds like you have multiple issues in your deployment. i would suggest you create a post in our [community forum](https://community.sonarsource.com), so that more people can have a look at it.

Please include the full error log in your post. from a first glance i would say one of the following env vars is wrong in your setup:
* `SONAR_JDBC_URL`
* `SONAR_JDBC_USERNAME`
* `SONAR_JDBC_PASSWORD`

you can find `sonar.properties` in the container in `/opt/sonarqube/conf/sonar.properties`

usually you don't have to set anything to `SONARQUBE_WEB_JVM_OPTS`. these are additional jvm parameter for the sonarqube application, so they should be in the form of `-Dsonar.property.name=value`, but there is a very limited use case for these. 

@nygage i will close this issue after 1 week without response. feel free to reopen this or even better create a post in the community forum
