### ISSUE TITLE
"TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark" from Elasticsearch

### ISSUE THREAD

**Issue by marcelstoer** [SonarSource/docker-sonarqube#506]
I kept getting this error in the Docker logs 

> 2021.09.17 13:42:03 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_AXvvAf2BhzHlkOqvLs6g], message [ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=index [rules] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];]]]

This mapped to this error displayed in the SonarQube GUI for an single analysis (the red bar showing "The Project Analysis has failed.")

> java.lang.IllegalStateException: Unrecoverable indexation failures: 1 errors among 1 requests
	at org.sonar.server.es.IndexingListener$1.onFinish(IndexingListener.java:39)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:131)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.doIndex(ProjectMeasuresIndexer.java:162)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.indexOnAnalysis(ProjectMeasuresIndexer.java:87)
	at org.sonar.ce.task.projectanalysis.step.IndexAnalysisStep.execute(IndexAnalysisStep.java:45)

After some digging I found the following 2 (ok, 3) commands executed in the container fixes this.

```
$ apk --no-cache add curl
$ curl -XPUT -H "Content-Type: application/json" http://localhost:9001/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
$ curl -XPUT -H "Content-Type: application/json" http://localhost:9001/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @marcelstoer ,

well the message is clear right? There is a threshold that is reached for the disk storage for ES. (95% per default). ES in SonarQube is holding your data, so with the modifications you did with curl, you removed this threshold, so you are now at risk that ES will grow to 100% of your available storage. This threshold is enforced for stability reasons and of cause you are free to remove it, but this is not advised and can render sonarqube unstable. 

the right fix for this issue is to resize your persistent storage on the host that is holding your docker volume for the ES indexes. When you have enough storage available, SQ will take care of re enabling read/write access to the ES indexes.

i am closing this issue as there is nothing wrong with the images or sonarqube. if you need additional help, feel free to head over to the [community forum](https://community.sonarsource.com/) and create a new thread there :slightly_smiling_face:

**Comment by marcelstoer** [comment]
Thanks for the feedback. Yes, the message is clear. I understand the implications.

Before I resorted to this workaround I checked the Docker storage on the host. It's got over 5GB extra available (disk image size) when SQ is running. Are you saying 5GB is not enough?

**Comment by tobias-trabelsi-sonarsource** [comment]
it is percentage based. so if 95% of 5 GB are used you will hit this threshold

**Comment by marcelstoer** [comment]
I now. Sorry if my message was confusing. I meant I have 5GB *free*.

**Comment by tobias-trabelsi-sonarsource** [comment]
If you have a 100 GB Storage device, then 95% is 95 GB of that device, meaning 5 GB are still free AND you would still hit this threshold. Does this example make sense? The total size does not matter in a percent based calculation.

**Comment by marcelstoer** [comment]
Well, in general I understand the difference between _relative_ and _absolute_ quite well 😄 I just didn't understand on what basis SQ runs theses calculations.

It dawned on me when I ran `df -h` in the container. 

As Docker mounts its overlay file system (i.e. the entire disk image size) to `/` in the container the percentage used was indeed high. That wasn't because of the SQ container but because I had a ton of unused images and stopped containers eating away at the same chunk of data. Doing a Docker system prune got rid of those - and made SQ happy again.

Thanks for your patience.
