### ISSUE TITLE
Multiple SAML Provider

### ISSUE THREAD

**Issue by Aloush-ha** [SonarSource/docker-sonarqube#581]
Hello

I have installed Sonarqube Communtiy 9.7.1 in our Kubernetes Cluster v1.21.14

my Plan to setup multiple SAML Provider (AZUR and OKTA) Togather on Sonarqube.
but the sonarqube propertier didn't have this possibility 
sonar.auth.saml.enabled
sonar.auth.saml.applicationId
sonar.auth.saml.providerName 
sonar.auth.saml.providerId 
sonar.auth.saml.loginUrl
sonar.auth.saml.user.login
sonar.auth.saml.user.name
sonar.auth.saml.user.email
sonar.auth.saml.group.name
sonar.auth.saml.certificate.secured

is there another way for that
thank you

**Comment by jCOTINEAU** [comment]
Dear @Aloush-ha 

thanks for raising this issue. We typically evaluate bug reports that are submitted through our [community forum](https://community.sonarsource.com/) and we invite you to do so.

Also that issue seems to be related to the SonarQube product itself and not the docker image, so posting on the community forum will allow you to get direct dev answer.

Given that a few months passed and a few releases were made in the meantime, is this issue still relevant?

Please also notice that a new SonarQube LTS version has been released! You can pull it from `sonarqube:9.9.0-<EDITION>`.
