### ISSUE TITLE
Dockerfile (community edition, 9) as of 03.01.2023 is not using environment variables

### ISSUE THREAD

**Issue by cbb-colab** [SonarSource/docker-sonarqube#593]
As documented in 
https://docs.sonarqube.org/latest/setup-and-upgrade/configure-and-operate-a-server/environment-variables/

SONARQUBE_JDBC_URL/SONARQUBE_JDBC_USERNAME/SONARQUBE_JDBC_PASSWORD

should be used to configure docker image to make use of e.g. external database.

Image instead is not using those variables when starting w/o the run.sh  but using

ENTRYPOINT ["/opt/java/openjdk/bin/java","-jar","lib/sonarqube.jar","-Dsonar.log.console=true"]

**Comment by jCOTINEAU** [comment]
Hello @cbb-colab thanks a lot for taking the time to participate in the community.

I am assuming you are building and testing it locally ? ( as it is still not published to dockerhub )

As per the documentation it should be ```SONAR_***``` and not ```SONARQUBE_***```

The goal is to make the Docker image behave exactly as SonarQube and not bundling specific compatibility script.

Those ```SONARQUBE_***``` env var as been deprecated since a long time, and that new LTS will mark the deletion of that feature

To give more context, we are still actively testing that image, and the documentation will be updated when it is push to prod.

Hope that answer your question, let me know if that fixes the issue.
