### ISSUE TITLE
Critical vulnerabilities with packages org.yaml/snakeyaml v1.33 and org.apache.sshd/sshd-common v2.8.0

### ISSUE THREAD

**Issue by grantg22** [SonarSource/docker-sonarqube#620]
Upon downloading the lts and latest docker images there are currently two critical vulnerabilities in both relating to the packages [org.yaml/snakeyaml version 1.33](https://dso.docker.com/packages/pkg:maven/org.yaml/snakeyaml/versions/1.33) and [org.apache.sshd/sshd-common version 2.8.0](https://dso.docker.com/packages/pkg:maven/org.apache.sshd/sshd-common/versions/2.8.0). 

It looks as if this issue can be resolved by updating the packages to the following versions if possible:

org.yaml/snakeyaml -> version 2.0
org.apache.sshd/sshd-common -> version 2.9.2

The Docker Image Vulnerability Database can be referenced at the links below.

[sonarqube:lts](https://dso.docker.com/images/sonarqube/digests/sha256:a4fafa6db5eee1e8d66b98a17a1d28620ea24404504a33f485aa05ae1e3d0ed0)
[sonarqube:latest](https://dso.docker.com/images/sonarqube/digests/sha256:2c5e3b810a45551b90ed117e890388e686c855b3262eec4fa1e52b33d2d8815b)

**Comment by jCOTINEAU** [comment]
hello @grantg22 thanks a lot for taking the time to participate in the community.

Those vulnerability come from the SonarQube dependencies and not from the Dockerfile system setup on top of it.

The SonarQube team monitor and updates those kind of vulnerabilities, if this is still relevant and has not been fixed in the latest SonarQube version, please open a thread directly on the [community forum](https://community.sonarsource.com/)

Based on that i will close this issue.

Thanks a lot again.
