### ISSUE TITLE
docker run -e 的参数是在哪里定义的？为什么有的可以有的不行

### ISSUE THREAD

**Issue by bobo2001281** [SonarSource/docker-sonarqube#622]
I execute the command and not use outside pg.
docker run -d --name sonarqube_test \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=jdbc:postgresql://1*.1*.1*.1*:5432/sonar \
    -e SONAR_JDBC_USERNAME=sonar \
    -e SONAR_JDBC_PASSWORD=***** \
    -v sonarqube_data_test:/opt/sonarqube/data \
    -v sonarqube_extensions_test:/opt/sonarqube/extensions \
    -v sonarqube_logs_test:/opt/sonarqube/logs \
    -v sonarqube_conf_test:/opt/sonarqube/conf \
    sonarqube:7.9.5-community

but I use this command and use the outside pg

docker run -d --name sonarqube \
    -p 9000:9000 \
    -e sonar.jdbc.url=jdbc:postgresql://1*.1*.1*.1*:5432/sonar \
    -e sonar.jdbc.username=sonar \
    -e sonar.jdbc.password=***** \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    -v sonarqube_conf:/opt/sonarqube/conf \
    sonarqube:7.9.5-community

1.What is the difference between ?
2.sonar.jdbc.url or SONAR_JDBC_URL  Where is it defined?
3.SONAR_JDBC_URL，This parameter cannot be used in version 7.9.5, but it is available in version 9.9.1.  why？

**Comment by jCOTINEAU** [comment]
Hello @bobo2001281 thanks a lot to take the time to participate in the community.

Let me clarify that behavior.

Sonarqube can be configured both with **env_var** and with command line arguments. For example `sonar.jdbc.url` is supposed to be a command line argument ( docker run sonarqube -Dsonar.jdbc.url=xxx ) not an **env_var**.

Nonetheless in the docker file, we had a compatibility script, checking for the **env_var** `sonar.jdbc.url` and injecting it as a command line argument. see [here](https://github.com/SonarSource/docker-sonarqube/blob/102e6fc9216ad9f32b5f48462fe9d1f30e401908/7/community/run.sh#L30) for details.

With newer version of the docker image (starting from 9.9.0) we removed that compatibility, so the docker image is configurable exactly as the SonarQube **product**.

on top of that **SONAR_JDBC_URL** is the preferred way of configuring that connection, and the variable might have been added during the 8.x cycle (I will have to double check) but this is why it does not exist in `7.9.5`.

Before it was named SONARQUBE_JDBC_URL but it has been deprecated since a long time.

Hope that answer your questions.

**Comment by poo0054** [comment]
I don't understand, this is what I was taught on the https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/ website.

```java
$> docker run -d --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=... \
    -e SONAR_JDBC_USERNAME=... \
    -e SONAR_JDBC_PASSWORD=... \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    <image_name>
```


```shell
[root@localhost ~]# docker run -d --name sonarqube -p 9000:9000 -e SONAR_JDBC_URL=jdbc:mysql://192.168.56.10:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false  -e SONAR_JDBC_USERNAME=root  -e SONAR_JDBC_PASSWORD=root    -v mydata/sonarqube/data:/opt/sonarqube/data -v mydata/sonarqube/extensions :/opt/sonarqube/extensions -v sonarqube_logs:/opt/sonarqube/logs    3f623568fa64
[1] 55102
[2] 55103
[3] 55104
[4] 55105
bash: -e: 未找到命令...
[2]   完成                  characterEncoding=utf8
[3]-  完成                  rewriteBatchedStatements=true
[2]   完成                  characterEncoding=utf8
[3]-  完成                  rewriteBatchedStatements=true
[4]+  完成                  useConfigs=maxPerformance
[root@localhost ~]# "docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image

[1]+  退出 1                docker run -d --name sonarqube -p 9000:9000 -e SONAR_JDBC_URL=jdbc:mysql://192.168.56.10:3306/sonar?useUnicode=true
```


I also don't know if mysql is supported, how do I do it and where is the documentation?

**Comment by nixel2007** [comment]
1. Your last arg does not looks like image name. Check it.
2. Support of mysql was dropped several releases ago.
3. All docs are in docs.sonarqube.org

**Comment by poo0054** [comment]
Thanks. Are there plans to add mysql later on. I guess I won't open a separate database for sonar if mysql is not supported

**Comment by nixel2007** [comment]
No, it was dropped completly.
