### ISSUE TITLE
Can't find rule `Promises should not be misused`

### ISSUE THREAD

**Issue by rohmansca** [SonarSource/docker-sonarqube#626]
Hi,
I'm using docker sonarqube version `10.0.0-community` on my local. 
I'm also using sonarcloud service.

I found a different rule between them. I can't find rule `Promises should not be misused` in docker sonarqube, but I can find it in sonarcloud. I also checked this rule on sonarsource, the same result with sonarcloud.

then, I searched it by key and got different result.
sonarqube result:
![Screen Shot 2023-05-29 at 10 44 00](https://github.com/SonarSource/docker-sonarqube/assets/78307609/8364c155-c46c-4380-8be3-91e67041d77d)

sonarcloud result:
![Screen Shot 2023-05-29 at 10 44 13](https://github.com/SonarSource/docker-sonarqube/assets/78307609/1efa45bc-281c-44e0-9a59-c679be6e7f05)

sonarsource result:
![Screen Shot 2023-05-29 at 10 47 41](https://github.com/SonarSource/docker-sonarqube/assets/78307609/1ce8372b-973e-4aae-a211-d0b362509041)

I'm not sure how to get the same result with the sonarcloud and sonarsource

**Comment by jCOTINEAU** [comment]
hello @rohmansca, thanks a lot to participate in the community.

Could you please fill a report directly in our community forum [here](community.sonarsource.com) ?

That docker repo mostly package the official SonarQube zip into a Docker image, but in that case it is not the root cause of the issue.

Our community forum is the way to go for reporting bugs on the SonarQube product,

Regards,
Jeremy

**Comment by rohmansca** [comment]
Thanks for your response @jCOTINEAU 
I'll fill my report to the community forum.
I think the link is wrong, is [this link](https://community.sonarsource.com/) correct?

**Comment by rohmansca** [comment]
move this to community forum [[ref](https://community.sonarsource.com/t/cant-find-rule-promises-should-not-be-misused/91749)]
