### ISSUE TITLE
Add an external plugin 

### ISSUE THREAD

**Issue by ridi-mz** [SonarSource/docker-sonarqube#63]
Hi, how can i add an external plugin (a jar file) to sonarqube in this configuration?

**Comment by thokari** [comment]
At least not by doing it naively through the UI, as this will destroy your container instance, because of missing permissions to write to /opt/sonarqube/temp .

What you would want to do instead is when provisioning/starting the container is create additional volumes, e.g. `/op/sonarqube/extensions` and then copy the .jar files for the plugins into the folders on the host, so that the container picks them up when starting.

**Comment by Godin** [comment]
See also https://github.com/SonarSource/docker-sonarqube/issues/87
