### ISSUE TITLE
Docker image deploy ulimit and baseos

### ISSUE THREAD

**Issue by vndroid** [SonarSource/docker-sonarqube#633]
Question 1:
According to the document https://docs.sonarsource.com/sonarqube/9.9/requirements/prerequisites-and-overview/ , 
> If the user running SonarQube (sonarqube in this example) does not have permission to have at least 131072 open descriptors, you must insert this line in /etc/security/limits.d/99-sonarqube.conf (or /etc/security/limits.conf as you wish):
> ```
> sonarqube   -   nofile   131072
> sonarqube   -   nproc    8192
> ```

if I deploy it with a Docker container, the sonarqube running user in container is `sonarqube`, but in the host system, it is my general user `kane`, 

```bash
$ ps -ef | grep sonarq
kane        5016    4994  0 Jul13 ?        00:05:32 /opt/java/openjdk/bin/java -jar lib/sonarqube.jar -Dsonar.log.console=true
```

So how should a system restriction policy be written? kane or sonarqube?

Question 2:
The sonarqube base image (in official docs) is ubuntu 22.04, but the base image has alpine branch [eclipse-temurin:17-jre-alpine](https://github.com/adoptium/containers/blob/15919f7dd6a903f0f966f484461954dcf7e28620/17/jre/alpine/Dockerfile.releases.full), why not use this branch base image?

**Comment by jCOTINEAU** [comment]
Dear @vndroid 

thanks again for posting this issue. We really value the input we get from our users and that's why we have a dedicated forum for it.

To centralize the triaging process and improve the way we handle these requests (e.g., new features or bugs), please create a new thread in our [forum](https://community.sonarsource.com/tags/c/sq/10/none/docker).

I will proceed by closing this issue.

Ps: to answer your second question, alpine and java does not works well under ARM64 architecture because the jvm is compiled againt musl libc instead of glibc. For that reason we decided to move to ubuntu eclipse temurin.
