### ISSUE TITLE
Cannot switch to Mysql Database

### ISSUE THREAD

**Issue by ovidiugrebenisan** [SonarSource/docker-sonarqube#67]
I have uncommented the mysql template line in /conf/sonar.properties (added user and password as well)but it start using the default H2 database anyway. I tested the same configuration locally and it stars fine.

**Comment by Godin** [comment]
@ovidiugrebenisan this is probably caused by the fact that this Docker image since its inception allows to specify `sonar.jdbc.url` via environment variable `SONARQUBE_JDBC_URL` - see [`run.sh`](https://github.com/SonarSource/docker-sonarqube/blob/bdf21686f162c5493bbd7388c666225fa16e3bd1/5.6.4-alpine/run.sh#L13). So for example you can either do
```
docker run -d --name sonarqube -p 9000:9000 sonarqube -Dsonar.jdbc.url=jdbc:mysql://...
```
either
```
docker run -e "SONARQUBE_JDBC_URL=jdbc:mysql://..." -d --name sonarqube -p 9000:9000 sonarqube
```
