### ISSUE TITLE
After restart docker plugins disappear

### ISSUE THREAD

**Issue by carloscds** [SonarSource/docker-sonarqube#73]
When I restart docker container, my plugins disappear.
I'm using a SQL Server database on hostmachine.

**Comment by nedvisol** [comment]
I have the same issue, but it happens when the container is destroyed and re-created pointing to the same-existing /opt/sonarqube/data volume.

**Comment by nedvisol** [comment]
I figured this out. /opt/sonarqube/extensions also needs to be persisted as Plugins are stored in this directory. When the container is rebuilt, this directory is set to the initial state without any plugins installed.

This is important for us since we're running Sonar in container management system where it can be moved between hosts automatically (persistent volumes are mounted via NFS.)

**Comment by carloscds** [comment]
@nedvisol I solve persinting this folder (/opt/sonarqube/extensions)
