### ISSUE TITLE
Docker container that includes specific plugins

### ISSUE THREAD

**Issue by javixeneize** [SonarSource/docker-sonarqube#87]
Hi

I would like to create a docker image with some specific plugins on it.

I know that it can be added later to the extensions volume, but i would like to have the image with those plugins already contained there

How should i do that? Should i modify the dockerfile to include the reference to those plugins?

Thanks

**Comment by cpettifer** [comment]
You could write your own Dockerfile that is "FROM sonarqube:6.3.1". As part of your Dockerfile you could either wget some plugins and put them into /opt/sonarqube/extensions/plugins or COPY them from your local disk into that folder. These will be picked up on startup by sonarqube.

I've written my own Dockerfile that essentially does this because it will be run on a host that does not have external network access, so the update centre won't work for me to download plugins. It's based on the 6.3.1-alpine Dockerfile at the moment, but only because I wanted to run 6.4 which has not been committed to github yet.
