### ISSUE TITLE
After analyze, "Project is not analyzed yet" error.

### ISSUE THREAD

**Issue by kahyalar** [SonarSource/docker-sonarqube#95]
Hey all, 
I'm using docker version of SonarQube. After i run `mvn sonar:sonar` at terminal i saw build successful. You can check report at xxx url. But in my projects page i saw "Project is not analyzed yet." at that project file.

Also, i'm not sure about is it fully analyze the whole code.
Waiting for your helps.
Thank you

**Comment by Godin** [comment]
This is an issue tracker of a Docker image. For the general questions about SonarQube please follow https://www.sonarqube.org/community/feedback/

Results of analysis are not available immediately, because they should also be processed on server, which takes time - see https://docs.sonarqube.org/display/SONAR/Analyzing+Source+Code
